name: Build Theos Tweak

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Theos & Dependencies
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          make clean
          make FINALPACKAGE=1
          mkdir -p output
          find .theos -name "*.dylib" -exec cp {} ./output/ \;

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: KeyChecker-Dylib
          path: output/*.dylib
